### PR TITLE
Added Getting Started with Python page

### PR DESCRIPTION
**Pull request by franTarkenton**
Hey Stephanie, Just put together a simple getting started with python page.  I put it in its own markdown file as the wiki part of the repo is not included when the repo is forked.  Let me know if you would like the contents supplied some other way.

Cheers, 
Kevin

### CODE REVIEW

**Comment by stephhazlitt** [comment]
Thanks @franTarkenton, very much appreciated! Any chance you could [clone the Wiki](https://github.com/bcgov/bcgov-data-science-resources/wiki) and add the content into the existing .md page for 'Getting Started with Python'? Or if you would prefer, I can add you as a contributor to the repo and you can add to the the wiki directly.

**Comment by franTarkenton** [comment]
Hey Stephanie, soo not sure the best way to contribute.  Sure wish the wiki portion of a repo supported pull requests!!  I think the only way that I can contribute is if you make me a contributor to the wiki.  

I was able to clone the wiki and make the changes locally, the problem that I run into is how to get the local changes back into the github wiki.  Currently when I try to push my changes back to https://github.com/bcgov/bcgov-data-science-resources.wiki.git I am getting "Permission denied" errors.

Let me know what the best way to do this is for you.

Cheers

Kevin

**Comment by stephhazlitt** [comment]
Hi @franTarkenton. I have given you collaborator access to the repository, so hopefully you can push the wiki changes you have made in your local version. We are still learning the nuances of the wiki feature, and have mostly all edited right in the GitHub web GUI thus far. You are leading the way! Thanks again for your contribution to the Python content.

**Comment by franTarkenton** [comment]
Awesome thanks Stephanie, Hooray!  I was able to push changes.  I believe the content is now there.  Cheers

**Comment by stephhazlitt** [comment]
Looks great in the [Wiki](https://github.com/bcgov/bcgov-data-science-resources/wiki/Getting-Started-with-Python). I will close this PR.

**Pull request closed without merging**
